# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package*.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Default command: run MCP server via stdio
CMD ["node", "dist/index.js"]
